### ISSUE TITLE
Omogućiti pretraživanje pizze s nazivom koji je djelomičan

### ISSUE THREAD

**Issue by sbuljat** [karlozrilic/rwa-projekt#3]
Koristiti LIKE ili sličan koncept kako bi mogli pretražiti nazive i s početnim slovima naziva.

**Comment by karlozrilic** [comment]
Moguće pretraživanje baze podataka s djelomičnim upisom npr. naziva

**Comment by sbuljat** [comment]
Ovakav pristup je prihvatljiv ako se zaista radi o 1-2 parametra pa if petlja to može riješiti, ali sve od 3 na više ima previše kombinacija koje čine kod manje čitljivim. Puno bi bolje bilo kad bi koristili kompoziciju pa da spremate rezultat svakog filtera u varijablu i u sljedećem koraku dodajete novi filter ako je parametar definiran. Jel Vam to ima smisla? Ako nije jasno možete me nazvati na telefon direktno, imate ga u Whatsapp grupi.

**Comment by sbuljat** [comment]
Dodajte još ovu izmjenu i to će biti za maksimalan broj bodova.

**Comment by karlozrilic** [comment]
Riješeno. Od sad ovisno je li unesen npr. naziv u query se dodaje filter za naziv umjesto 28 linija koda if petlji.

**Comment by sbuljat** [comment]
Super. Ocjena je dodana.
