### ISSUE TITLE
Spojiti "/api/list-pizzas" i "/api/pizzas" u jedan API [opcionalno]

### ISSUE THREAD

**Issue by sbuljat** [karlozrilic/rwa-projekt#4]
Ovo je opcionalan zadatak, ali bilo bi korisno vidjeti jel se mogu oba API-ja spojiti u jedan. Odnosno da API zna koju razinu ovlasti korisnik ima pa da ovisno o tome je li ADMIN ili ne ima drugačije ponašanje.

**Comment by karlozrilic** [comment]
Ovaj dio nisam uspio napraviti
